package/spidermonkey185: new package
This is the old 1.8.5 branch of spidermonkey, used in Firefox 4.
It is rather unmaintained, but some software still depend on it,
such as couchdb.

Signed-off-by: Nicolas Cavallari <nicolas.cavallari@green-communications.fr>

Bernd: Updated the patch by Nicolas
- rebased
- switched python to python3
- added myself to DEVELOPERS
- updated patches to solve build problems found by test-pkg
  - patches 1-10 were taken from Fedora:
    https://src.fedoraproject.org/rpms/js/tree/f26
  - patches 11 & 13 are from Nicolas original patch series
  - patch 12 was added to fix armv5 support
  - patch 14 fixes build with gcc 14.x
- HOST_CFLAGS was added to fix configure errors detected by test-pkg:
  - br-arcle-hs38:
    gcc: error: unrecognized command line option '-matomic';
    did you mean '-mbionic'?
  - br-xtensa-full:
    gcc: error: unrecognized command line option '-mlongcalls'
    gcc: error: unrecognized command line option '-mauto-litpools'
  - powerpc-ctng_e500v2-linux-gnuspe:
    gcc: error: unrecognized argument in option '-mabi=spe'
    gcc: note: valid arguments to '-mabi=' are: ms sysv
    gcc: error: unrecognized command line option '-mfloat-gprs=double';
    did you mean '-ffloat-store'?
- JIT support was disabled for BR2_ARM_CPU_ARMV4 to fix:
  {standard input}:35: Error: selected processor does not support ARM mode `blx SetVMFrameRegs'
  {standard input}:37: Error: selected processor does not support ARM mode `blx PushActiveVMFrame'
  {standard input}:46: Error: selected processor does not support ARM mode `blx PopActiveVMFrame'
  {standard input}:55: Error: selected processor does not support ARM mode `blx js_InternalThrow'
  {standard input}:60: Error: selected processor does not support ARM mode `blx PopActiveVMFrame'
  {standard input}:69: Error: selected processor does not support ARM mode `blx ip'
  config/rules.mk:1475: recipe for target 'MethodJIT.o' failed
- test-pkg also detected build errors on powerpc and x86_64:
  jsapi.cpp: In function ‘JSBool JS_ConvertArgumentsVA(JSContext*, uintN, jsval*, const char*, __va_list_tag*)’:
  jsapi.cpp:361:63: error: cannot convert ‘__va_list_tag**’ to ‘__va_list_tag (*)[1]’
   for argument ‘5’ to ‘JSBool TryArgumentFormatter(JSContext*, const char**, JSBool, jsval**, __va_list_tag (*)[1])’
                                       JS_ADDRESSOF_VA_LIST(ap))) {
  which were fixed by ac_cv_va_val_copy=no

Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>