package/python-scipy: remove license file
Buildroot commit 5d695881f8dc68ff1efe2cce75dda462c5990e3c bumped the
package from 1.16.3 to 1.17.1. In Version 1.17.0 upstream removed the
license file scipy/sparse/linalg/_eigen/arpack/ARPACK/COPYING:
https://github.com/scipy/scipy/commit/14dffda0b83c46728a7c88998804a4663bb735b3

causing an error with make target python-scipy-legal-info:

ERROR: while checking hashes from package/python-scipy/python-scipy.hash
ERROR: scipy/sparse/linalg/_eigen/arpack/ARPACK/COPYING has wrong sha256 hash:
ERROR: expected: 0926566f9f406178d1214f8cc796e166b1213dd7c05e0c5b461a8b8ac9e50bbe
ERROR: got     :
ERROR: Incomplete download, or man-in-the-middle (MITM) attack

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>