package/util-linux: bump version to 2.42.2
https://www.kernel.org/pub/linux/utils/util-linux/v2.42/v2.42.2-ReleaseNotes
https://www.kernel.org/pub/linux/utils/util-linux/v2.42/v2.42.1-ReleaseNotes
https://www.kernel.org/pub/linux/utils/util-linux/v2.42/v2.42-ReleaseNotes

Removed patches which were applied upstream, also remove autoreconf.

Patch 0001 was applied as
https://github.com/util-linux/util-linux/commit/57dab03caf941bf01544cc4548e36cc0c3357d2c
after the rename of the original header with commit
https://github.com/util-linux/util-linux/commit/f419d67de67610180fb04e64d21323ce8927d31d

Added Config.in options for new commands copyfilerange & getino.

copyfilerange is broken according to the Gitlab pipelines only with the
br-arm-full-static defconfig:

  configure: WARNING: Unable to detect syscall copy_file_range.
  configure: error: copyfilerange selected but copy_file_range syscall
    not found

because this defconfig uses kernel headers version 4.4.
copy_file_range() was added to Linux in version 4.5 with commit
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=29732938a6289a15e907da234d6692a2ead71855
so we require kernel headers >= 4.5 for copyfilerange.

getino builds when current uClibc is built from source but fails on the
Gitlab pipelines with all uClibc-based toolchains:

  configure: error: getino selected, but required statx function not
    available

so we disable getino for uClibc for now.

This bump adds fanotify support in libmount:
https://github.com/util-linux/util-linux/commit/e3e54259e780138d0c7941bbdcb0723bb279516c
which will cause build errors with uClibc < 1.0.58 as detected by the
Gitlab pipelines:

  libmount/src/monitor_fanotify.c:33:43: error: field ‘hdr’ has
    incomplete type
   33 |         struct fanotify_event_info_header hdr;

because fanotify_event_info_header was added to uClibc 1.0.58:
https://github.com/wbx-github/uclibc-ng/commit/c08beaadc9100f7062d9cfbfec7cc9ba2b0b38fe

so we disable this code for uClibc for now.

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>