package/freerdp: fix build with ffmpeg 8.0
Added four upstream patches backported from FreeRDP 3.x.

The remaining build error:

/home/bernd/buildroot/output/build/freerdp-2.11.7-18-g0ee17e2f8e49d56ab5b90d5160fa8f87ffc445e0/
 channels/client/tables.c:129:22:
 error: initialization of ‘UINT (*)(void)’ {aka ‘unsigned int (*)(void)’}
 from incompatible pointer type ‘UINT (*)(void *)’ {aka ‘unsigned int (*)(void *)’}
 [-Wincompatible-pointer-types]
  129 |         { "oss", "", oss_freerdp_rdpsnd_client_subsystem_entry },

is fixed by adding -Wno-incompatible-pointer-types to CFLAGS due to
tables.c being dynamically created during the build and backporting the
supposed upstream fix
https://github.com/FreeRDP/FreeRDP/commit/fe6d861a5c21edf5341ec203a12d6f62f8a80367
is too invasive.

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>