package/x265: bump version to 4.2
https://mailman.videolan.org/pipermail/x265-devel/2026-April/014533.html

Rebased patch 0001.
Removed remaining patches which are included in this release.

Added dependency to _SYNC_8 for cli due to upstream commit
https://bitbucket.org/multicoreware/x265_git/commits/7ea54bdf5a6a35e3fff44d8454e31695928dc752#Lsource/common/threading.hT70

This bump includes upstream commit
https://bitbucket.org/multicoreware/x265_git/commits/f74b2f38ad850a09524f331f64870e6300fd923b
that uses vst1q_s16_x2() which was first added to gcc 9:
https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=568421baa5a4cdb7bb7c5ac323c939492ee3f052

causing build errors detected by the Gitlab pipelines:
/builds/bkuhls/buildroot/br-test-pkg/bootlin-aarch64-glibc-old/build/x265-4.2/source/common/aarch64/pixel-prim.cpp:936:25:
 error: ‘vst1q_s16_x2’ was not declared in this scope

Disable asm for i386 with musl toolchains to fix linking error detected
by the Gitlab pipelines:

/builds/bkuhls/buildroot/br-test-pkg/bootlin-x86-i686-musl/build/x265-4.2/source/common/x86/cpu-a.asm:181:
 error: ELF format cannot produce non-PC-relative PLT references

Partly reverting
https://bitbucket.org/multicoreware/x265_git/commits/b2950952dcbb28f7aa053e84663c384064c88a4e

does not fix the problem but shows:

/home/bernd/buildroot/buildroot/output/per-package/x265/host/opt/ext-toolchain/bin/../lib/gcc/i686-buildroot-linux-musl/14.3.0/../../../../i686-buildroot-linux-musl/bin/ld:
 common/CMakeFiles/common.dir/x86/pixel-a.asm.o:
 warning: relocation in read-only section `.text'
[ 86%] Built target x265-static
/home/bernd/buildroot/buildroot/output/per-package/x265/host/opt/ext-toolchain/bin/../lib/gcc/i686-buildroot-linux-musl/14.3.0/../../../../i686-buildroot-linux-musl/bin/ld:
 read-only segment has dynamic relocations

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>