package/util-linux: bump version to 2.42.3
https://www.kernel.org/pub/linux/utils/util-linux/v2.42/v2.42.3-ReleaseNotes
https://www.kernel.org/pub/linux/utils/util-linux/v2.42/v2.42.2-ReleaseNotes
https://www.kernel.org/pub/linux/utils/util-linux/v2.42/v2.42.1-ReleaseNotes
https://www.kernel.org/pub/linux/utils/util-linux/v2.42/v2.42-ReleaseNotes

Removed patches which were applied upstream, also remove autoreconf.

Patch 0001 was applied as
https://github.com/util-linux/util-linux/commit/57dab03caf941bf01544cc4548e36cc0c3357d2c
after the rename of the original header with commit
https://github.com/util-linux/util-linux/commit/f419d67de67610180fb04e64d21323ce8927d31d

Added upstream commit to fix build with older glibc.

Added Config.in options for new commands copyfilerange & getino.

copyfilerange is broken according to the Gitlab pipelines only with the
br-arm-full-static defconfig:

  configure: WARNING: Unable to detect syscall copy_file_range.
  configure: error: copyfilerange selected but copy_file_range syscall
    not found

because this defconfig uses kernel headers version 4.4.
copy_file_range() was added to Linux in version 4.5 with commit
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=29732938a6289a15e907da234d6692a2ead71855
so we require kernel headers >= 4.5 for copyfilerange.

getino builds when current uClibc-ng is built from source but fails on
the Gitlab pipelines with all uClibc-ng-based toolchains:

  configure: error: getino selected, but required statx function not
    available

so we disable getino for uClibc-ng for now.

This bump adds fanotify support in libmount:
https://github.com/util-linux/util-linux/commit/e3e54259e780138d0c7941bbdcb0723bb279516c
which will cause build errors with uClibc-ng < 1.0.58 as detected by the
Gitlab pipelines:

  libmount/src/monitor_fanotify.c:33:43: error: field ‘hdr’ has
    incomplete type
   33 |         struct fanotify_event_info_header hdr;

because fanotify_event_info_header was added to uClibc-ng 1.0.58:
https://github.com/wbx-github/uclibc-ng/commit/c08beaadc9100f7062d9cfbfec7cc9ba2b0b38fe

so we disable this code for uClibc-ng for now.

Fixes the following CVEs:

 CVE-2026-76642 - mount(8) post-mount hooks execute after helper failure.
   When an external mount.<type> helper exits nonzero, post-mount hooks
   (X-mount.idmap, X-mount.owner/group/mode) still execute as if the
   mount had succeeded, allowing privileged operations on the
   pre-existing target filesystem.

 CVE-2026-78410 - mount(8) TOCTOU race on source path.
   In restricted (SUID, non-root) mode, the source path is
   canonicalized with realpath() as euid=0, following symlinks through
   user-writable directories.  Additionally, open_tree() follows
   symlinks in intermediate path components.  A local attacker can
   redirect a privileged mount or post-mount ownership change to an
   arbitrary path.

 CVE-2026-78409 - mount(8) X-mount.subdir symlink escape.
   The open_tree() call used to open a subdirectory on a detached mount
   follows symlinks in intermediate path components, allowing escape
   from the detached tree.

 CVE-2026-78408 - nsenter(1), unshare(1) file descriptor leak.
   File descriptors in nsenter and unshare were not created with
   O_CLOEXEC, potentially leaking them across exec.  Added O_CLOEXEC
   as defense in depth.

 wall(1), write(1) - hostname escape sequence injection.
   The CVE-2024-28085 fix sanitized only message bodies; the banner
   headers still interpolated the system hostname without sanitization.
   An unprivileged user can inject terminal escape sequences via a user
   namespace hostname.
   Additional fix for CVE-2024-28085.
   Reported-by: Skyler Ferrante

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>